services:
  vipe:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: vipe:latest
    restart: unless-stopped
    network_mode: host
    ipc: host
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all     # <-- only use cuda:1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - VGL_DISPLAY=${RENDER_DISPLAY:-":1"}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - $ROOT_DIR/:/home/user/km-vipe
      - .cache/:/home/user/.cache/
      - .models_cache/:/root/.cache/
      - $DATA_DIR/:/data
    runtime: nvidia
    privileged: true
    command: bash

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']       # <-- pin to GPU 1
              capabilities: [gpu]
