services:
  vipe:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: vipe:latest
    restart: unless-stopped
    network_mode: host
    ipc: host
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
      - VGL_DISPLAY=${RENDER_DISPLAY:-":1"}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - ./:/home/docker_user/ViPE
      - .cache/:/home/docker_user/.cache
    runtime: nvidia
    privileged: true
    command: bash